let nome1 = ('José')
let sobrenome1 = ('da Silva') 
let idade1 = (27)
let peso1 = (83.5)
let altura1 = (1.70)
let IMC1 = peso1/(altura1*2)

let nome2 = ('Carlos')
let sobrenome2 = ('de Souza')
let idade2 = (28)
let peso2 = (80.1)
let altura2 = (1.76)
let IMC2 = peso2/(altura2*2)

let nome3 = ('Aline')
let sobrenome3 = ('Ferreira')
let idade3 = (33)
let peso3 = (63.7)
let altura3 = (1.53)
let IMC3 = peso3/(altura3*2)

let nome4 = ('Ana') 
let sobrenome4 = ('Paula')
let idade4 = (26)
let peso4 = (55.0)
let altura4 = (1.62)
let IMC4 = peso4/(altura4*2)

console.log (nome1, sobrenome1, 'tem', idade1, 'anos, e seu IMC é ',IMC1 )
console.log (nome2, sobrenome2, 'tem', idade2, 'anos, e seu IMC é ',IMC2 )
console.log (nome3, sobrenome3, 'tem', idade3, 'anos, e seu IMC é ',IMC3 )
console.log (nome4, sobrenome4, 'tem', idade4, 'anos, e seu IMC é ',IMC4 )